### ISSUE TITLE
Cache behavior for 206 responses that includes etags needs investigation

### ISSUE THREAD

**Issue by shagamemnon** [cloudflare/kv-asset-handler#167]
#133, which enables etag support for all resource types hasn't been merged. When a strong `etag` is presented, partial responses to byte range requests are cached. However when weak `etags` are served, partial responses to range requests are not cached.

The resource types that will gain etag support when #133 is merged, and cache behavior on CF, Chromium and Safari, need to be investigated before #165 can be merged

_Originally posted by @shagamemnon in https://github.com/cloudflare/kv-asset-handler/issues/165#issuecomment-774694695_

**Comment by signalnerve** [comment]
Hey @shagamemnon, will this be fixed by #133?

**Comment by shagamemnon** [comment]
Any details on the possible Safari bug?

**Comment by b0ric** [comment]
Yes, still facing issues in Safari because kv-asset-handler does not respond with the correct byte range.
The PRs mentioned seems to fix request/response headers and the case when data has already been cached. To implement correct response had to go with the fix proposed by @cpauwels here: https://github.com/cloudflare/kv-asset-handler/issues/63#issuecomment-562482660
Though it may not be ideal and Streams API might be a better idea.

**Comment by Cherry** [comment]
Thanks for the info all. 

If anyone has any suggestions for a good way to implement this, I'd be very interested.

**Comment by b0ric** [comment]
Yes, it only affects Safari, both Desktop and Mobile. The latter means a video on your website won't work on Apple tablets and phones, in any browser.

**Comment by shagamemnon** [comment]
Can we close out this issue? I believe it was fixed with #133

**Comment by Cherry** [comment]
> Can we close out this issue? I believe it was fixed with #133

I'm pretty sure it's still an issue with Safari from what I've read here and some mentions in the Discord. I've yet to test it myself though unfortunately.
